name: CI-CD
on:
  pull_request:
    branches:
      - main
      - stage
      - develop

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
 
  CD:
    runs-on: ubuntu-latest
      
    steps:
      - name: Obter o código do projeto
        uses: actions/checkout@v4.2.2

      - name: Autenticar na AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/${{ secrets.AWS_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
